<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="6.574" tests="2" failures="1">
  <testsuite name="Root Suite" timestamp="2023-10-26T14:43:17" tests="0" file="cypress\e2e\todo.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="example to-do app" timestamp="2023-10-26T14:43:17" tests="2" time="6.561" failures="1">
    <testcase name="example to-do app pass - can add new todo items" time="1.478" classname="pass - can add new todo items">
    </testcase>
    <testcase name="example to-do app fail - can check an item as completed" time="0.000" classname="fail - can check an item as completed">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;li.completed&gt;&apos; to have class &apos;completedd&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<li.completed>' to have class 'completedd'
    at Context.eval (webpack://cypress_example/./cypress/e2e/todo.cy.js:26:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>